### ISSUE TITLE
Валидация

### ISSUE THREAD

**Issue by deuxego** [DIY0R/nestjs-rabbitmq#263]
Здравствуй, есть наработки по декораторам для валидации DTO?

**Comment by DIY0R** [comment]
**Thank you for your question!**  
Unfortunately, this functionality is not available at the moment. However, I plan to add a special decorator for validation using `class-validator` for DTOs in the near future.   In the meantime, you can use your own custom solution with [middleware](https://github.com/DIY0R/nestjs-rabbitmq?tab=readme-ov-file#middleware)
